version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: word_press
      WORDPRESS_DB_PASSWORD: SPKlw07*
    volumes:
      - /home/car/wordpress/volumes/wordpress_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - wordpress_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SPKlw07*
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: word_press
      MYSQL_PASSWORD: SPKlw07*
    volumes:
      - /home/car/wordpress/volumes/mysql_data:/var/lib/mysql
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  mysql_data:

networks:
  wordpress_network:
    driver: bridge
