---
- name: Install and start NGINX on EC2
  hosts: webserver
  become: true

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes
